version: '3.4'
services:
  reverse-proxy:
    image: traefik:2.9
    command: --api.insecure=true --providers.docker
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - "8080:8080"
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
  nextjs:
    container_name: nextjs
    build: ./nextjs
    ports:
      - "3000:3000"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.my-app.rule=Host(`reinrensen.nl`, `www.reinrensen.nl`)'
      - 'traefik.http.routers.my-app.tls=true'
      - 'traefik.http.routers.my-app.tls.certresolver=lets-encrypt'
      - "traefik.http.services.simple-nextjs.loadbalancer.server.port=3000"
